### ISSUE TITLE
Data View: Instance Identifier drop-down becomes uneditable post first selection

### ISSUE THREAD

**Issue by manankalra** [erasmoartur/attribute-radviz#1]
![Screenshot 2020-05-04 at 2 04 29 AM](https://user-images.githubusercontent.com/12759088/80930478-c4dd8f80-8dab-11ea-8c2d-049c79c7cb27.png)

![Screenshot 2020-05-04 at 2 06 50 AM](https://user-images.githubusercontent.com/12759088/80930523-f8b8b500-8dab-11ea-8b91-959ecd865f59.png)

**Comment by erasmoartur** [comment]
I believe I did it on purpose at the time. I do not remember the reason, but I will fix it soon.

**Comment by manankalra** [comment]
Closing this as the Instance Identifier drop-down is now editable.
