### ISSUE TITLE
Attribute View: Removing a category from a target attribute, removes that category from other attributes as well. 

### ISSUE THREAD

**Issue by shubham-kajaria** [erasmoartur/attribute-radviz#4]
Steps to reproduce this issue:
1. Load the dataset given below by loading it in .csv format
[Check.xlsx](https://github.com/erasmoartur/attribute-radviz/files/4724018/Check.xlsx)

Smoke: 0 -> doesn't smoke, 1 -> Smoke
Age group: 0 -> 10-15(years), 1 -> (15-20), 2 -> (20-25)
Married: -> 0 -> No, 1 -> Yes

2. Select the target attribute Agegroup and remove category 0 by dragging it out. We are left with two categories i.e. Agegroup with 15-20 and 20-25 years old.

3. Select another target attribute let's say, Smoke, I found out there is no category "0" in here which means whatever attributes I select as a target attribute there won't be any "0" category.

Different attributes have different meanings for "0" category:
But in this case, regardless of the meaning behind the category, it will remove 0 categories from the attributes which we select as a target attribute.

What I think the ideal scenario would be is:
Delete rows containing "0" category for that particular column only.
If we remove let's say Agegroup with "0" category, so rows with people aged between 10-15 only should be deleted from the dataset.
And when I select other attributes like Smoke, then Agegroup aged 10-15 years records only should be deleted regardless of whether he smoke or not.
So, other Age group people who do not smoke should be visible which means the "0" category of smoke would be deleted for the age group 10-15 years only. For other age groups, "0" category would be visible.

I hope I am able to explain the issue.

**Comment by erasmoartur** [comment]
Hello Shubham,

Sorry for the delay, and thank you for reproducing the issue in detail.

You're right. After removing one or more labels, the change of the target attribute has been confusing the next renderings. 

The problem occurred because I did not store the reference of the previous targets, so the filter happened on the current one.

An updated version was uploaded.

**Comment by shubham-kajaria** [comment]
Thanks for the update.

Regards,
Shubham
